
name: Build Image
on:
  push:
    branches:
      - main
      - feature/**
    paths-ignore:
      - '.github/workflows/*'
  workflow_dispatch:


permissions:
  contents: read

jobs:
  lint:
    name: Static code analys
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: action/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: run analysis with pylint
      run: |
        pylint $( git ls-files '*.py')
        
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: run unit tests
      run: |
        docker build --target test .


